export const teams = [
  { team: "Real Madrid", country: "Spain" },
  { team: "Manchester City", country: "United_Kingdom" },
  { team: "Bayern Munich", country: "Germany" },
  { team: "Paris Saint-Germain", country: "France" },
  { team: "Inter Milan", country: "Italy" },
  { team: "Benfica", country: "Portugal" },
  { team: "Ajax", country: "Netherlands" },
  { team: "Palmeiras", country: "Brazil" },
  { team: "River Plate", country: "Argentina" },
  { team: "Red Bull Salzburg", country: "Austria" },
  { team: "Club Brugge", country: "Belgium" },
  { team: "Dynamo Kyiv", country: "Ukraine" },
  { team: "FC Copenhagen", country: "Denmark" },
  { team: "Olympiacos", country: "Greece" },
  { team: "Galatasaray", country: "Turkey" },
  { team: "FC Zurich", country: "Switzerland" },
  { team: "Slavia Prague", country: "Czechia" },
  { team: "Dinamo Zagreb", country: "Croatia" },
  { team: "Red Star Belgrade", country: "Serbia" },
  { team: "Malmö FF", country: "Sweden" },
  { team: "Rosenborg", country: "Norway" },
  { team: "Ludogorets", country: "Bulgaria" },
  { team: "Ferencváros", country: "Hungary" },
  { team: "Maccabi Haifa", country: "Israel" },
  { team: "Sheriff Tiraspol", country: "Moldova" },
  { team: "Al Ahly", country: "Egypt" },
  { team: "Al Hilal", country: "Saudi Arabia" },
  { team: "Seattle Sounders", country: "United_States" },
  { team: "Urawa Red Diamonds", country: "Japan" },
  { team: "Wydad Casablanca", country: "Morocco" },
  { team: "Auckland City", country: "New_Zealand" },
];
